project:
  type: website
  output-dir: docs

# Meta
description-meta: "Academic Website of Felix Schönbrodt"
author-meta: "Felix Schönbrodt"

website:
  title: "Felix Schönbrodt"
  image: "https://quarto.org/quarto.png"
  description: "Academic Website of Felix Schönbrodt"
 
  navbar:
    background: light

    left:
#      - text: Home
#        href: index.qmd
      # - text: Abouthttps://www.nicebread.de/wp-content/uploads/2021/11/rt_logo_wide.png
      #   menu:
      #     - text: News
      #       href: posts.qmd#category=news
      #     - text: Events
      #       href: posts.qmd#category=event                             
      - text: Publications      
        href: publications.qmd
      - text: CV
        href: CV.qmd
      - text: Service to the field
        href: service.qmd
      - text: Funded Projects
        href: projects.qmd
      # - text: Research
      #   menu:          
      #     - text: Selected Papers
      #       href: posts.qmd#category=paper
      #     - text: Grants
      #       href: projects.qmd                                
      # - text: Teaching
      #   href: teaching.qmd                 

    right: 
      - icon: github
        href: https://github.com/nicebread
        target: _blank
      - text: "{{< fa brands mastodon >}}" 
        href: https://scicomm.xyz/@nicebread
        target: _blank   
      # - icon: rss
      #   href: posts.xml
      #   target: _blank
  
  page-navigation: false
  
  page-footer: 
    left: "[Felix Schönbrodt](https://www.nicebread.de) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: ""
    right:  
      - icon: github
        href: https://github.com/nicebread
        target: _blank
      - text: "{{< fa brands mastodon >}}" 
        href: https://scicomm.xyz/@nicebread
        target: _blank
      # - icon: rss
      #   href: posts.xml
      #   target: _blank  
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: false

  draft-mode: unlinked
  
  repo-url: https://github.com/nicebread/nicenet2025
# repo-actions: [edit, issue, source]
  
  open-graph: true

  site-url: https://www.nicebread.de
  
bibliography: references.bib

format:
  html:
    theme: 
      light: spacelab
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    include-in-header: 
      - files/includes/_academic.qmd
      - files/includes/matomo.html
    df-print: paged  # Enables interactive tables


