project:
  type: website
  output-dir: docs

# Meta
description-meta: "Academic Website of Felix Schönbrodt"
author-meta: "Felix Schönbrodt"

website:
  title: "Felix Schönbrodt"
  image: "https://quarto.org/quarto.png"
  description: "Academic Website of Felix Schönbrodt"
 
  navbar:
    background: light

    left:
#      - text: Home
#        href: index.qmd
      - text: About
        menu:
          - text: News
            href: posts.qmd#category=news
          - text: Events
            href: posts.qmd#category=event      
          - text: Contact
            href: contact.qmd             
      - text: Publications
        href: publications.qmd
      - text: Research
        menu:          
          - text: Selected Papers
            href: posts.qmd#category=paper
          - text: Grants
            href: projects.qmd                                
      - text: Teaching
        href: teaching.qmd                 

    right: 
      - icon: github
        href: https://github.com/nicebread
        target: _blank
      - text: "{{< fa brands mastodon >}}" 
        href: https://scicomm.xyz/@nicebread
        target: _blank   
      - icon: rss
        href: posts.xml
        target: _blank
  
  page-navigation: true
  
  page-footer: 
    left: "[Your Name](http://www.github.com) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: "Build on [Quart Academic Website Template](https://github.com/drganghe/quarto-academic-website-template) adapted by [Dr. Gang He](http://drganghe.github.io)"
    right:  
      - icon: github
        href: https://github.com/nicebread
        target: _blank
      - text: "{{< fa brands mastodon >}}" 
        href: https://scicomm.xyz/@nicebread
        target: _blank
      - icon: rss
        href: posts.xml
        target: _blank  
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  draft-mode: unlinked
  
#  repo-url: https://github.com/drganghe/quarto-academic-website-template
#  repo-actions: [edit, issue, source]
  
  open-graph: true
    
  # site-url: "https://drganghe.github.io/quarto-academic-website-template"
  
bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"

