---
title: ""
description-meta: "Curriculum Vitae"
title-block-banner: false
---

## Curriculum Vitæ

| Year            | Position/Title                                                                                                                                                                                                                                    |
| --------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **2020**        | Appointed as **professor** ("apl. Prof")                                                                                                                                                                                                          |
| **since 2018**  | **Akademischer Rat auf Lebenszeit** at Ludwig-Maximilians-Universität München, [Quantitative Methods and Assessment (Psychologische Methodenlehre und Diagnostik)](http://www.psy.lmu.de/pm/personen/lehrstuhlmitarbeiter/schoenbrodt/index.html) |
| **since 2017**  | **Managing director** of the [LMU Open Science Center](https://www.osc.uni-muenchen.de/index.html)                                                                                                                                                |
| **2016**        | **Akademischer Rat** a.Z. at Ludwig-Maximilians-Universität München, [Quantitative Methods](http://www.psy.lmu.de/pm/personen/lehrstuhlmitarbeiter/schoenbrodt/index.html)                                                                        |
| **2015-2016**   | **Visiting professor** (W3-Vertretungsprofessur) at Friedrich-Alexander-Universität Erlangen-Nürnberg                                                                                                                                             |
| **2014**        | **Habilitation (Dr. habil.)** and “Privatdozent” PD at Ludwig-Maximilians-Universität München                                                                                                                                                     |
| **2010 – 2016** | **Akademischer Rat** a.Z. at Ludwig-Maximilians-Universität München, Emotion and Motivation (Allgemeine Psychologie II)                                                                                                                           |
| **2010**        | **Dr. rer. nat.** (*summa cum laude*), supervised by Prof. Dr. Jens B. Asendorpf (Humboldt-University Berlin). Thesis: “Transference of relationship qualities to a virtual spouse”                                                               |
| **2007-2010**   | PhD scholarship from Studienstiftung des deutschen Volkes                                                                                                                                                                                         |
| **2009**        | Research stay at New York State University (Stony Brook)                                                                                                                                                                                          |
| **2008**        | Concession for psychotherapy (HPG)                                                                                                                                                                                                                |
| **2000 – 2006** | **Diploma** in psychology, Saarland University, Germany. Diploma thesis: “Development of a questionnaire for the Zurich Model of Social Motivation”                                                                                               |
| **1999-2000**   | Community service (“Zivildienst”) in a home for people with disabilities                                                                                                                                                                          |
| **1990-1999**   | Rudolf-Diesel-Gymnasium, Augsburg                                                                                                                                                                                                                 |


## Awards and Scholarships

| Year        | Award |
|-------------|-------------|
| **2022**        | DGPs [Förderpreis für Qualitätssicherung in der Psychologie](https://www.dgps.de/die-dgps/preise-und-ehrungen/foerderpreis-qualitaetssicherung-in-der-psychologie/) |
| **2016**        | [Leamer-Rosenthal Prize for Open Social Science](http://www.bitss.org/people/felix-schonbrodt/), awarded from the [Berkeley Initiative for Transparency in the Social Sciences](http://www.bitss.org/) (10,000 €) |
| **2016**        | [Award for good teaching](files/images/Schoenbrodt_teaching_prize_Bavaria.jpg) from the federal ministry of education (5000 €) |
| **2015**        | Best Paper Award from the [Journal of Research in Personality](http://www.journals.elsevier.com/journal-of-research-in-personality/awards/journal-of-research-in-personality-2015-best-paper-awards/) |
| **2014**        | Department’s [Award for Excellent Teaching](files/images/Schoenbrodt_Fakultaetspreis_Gute_Lehre.JPG) |
| **2010**        | Grant from “Google Summer of Code” for programming a statistical software (“TripleR: A package for social relations analyses”) |
| **2007 – 2010** | PhD scholarship from Studienstiftung des deutschen Volkes |
| **2009**        | Scholarship for research stay at the State University of New York, USA |
| **2007**        | Stipend from International Society for Human Ethology (ISHE) |
| **2006**        | Stipend from Volkswagen-Stiftung for a summer school “Evolutionary Anthropology” |